name: Build and Deploy ASP.NET Core App to Azure Web App - jus365

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Publish with dotnet
        run: dotnet publish -c Release -o ./myapp

      - name: Get repository root
        run: echo "::set-output name=repo_root::$(git rev-parse --show-toplevel)"
        id: get_root

      - name: Set project path
        run: echo "::set-output name=project_path::${{ steps.get_root.outputs.repo_root }}/Jus 365.csproj"
        id: set_project_path

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'jus365'
          slot-name: 'production'
          package: .
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_5f50f15d78ea413f9dd0fc710fd36446 }}

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      - name: Apply Entity Framework Core Migrations
        run: |
          dotnet ef database update --project "${{ steps.set_project_path.outputs.project_path }}" --context ApplicationDbContext
        env:
          ASPNETCORE_ENVIRONMENT: 'Production'
          ConnectionStrings__DefaultConnection: ${{ secrets.DefaultConnection }}
