name: Build and Deploy ASP.NET Core App to Azure Web App - jus365

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Publish with dotnet
        run: dotnet publish -c Release -o ./myapp

      - name: List contents of working directory (verification)
        run: dir ./  # Optional verification step
        shell: pwsh  # Optional for PowerShell commands

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4  # Ensure compatible versions used here and in deploy job
        with:
          name: .net-app  # Ensure consistent name
          path: ./myapp

  deploy:
    runs-on: windows-latest
    needs: build  # This job depends on the successful completion of the "build" job
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4  # Ensure compatible versions used here and in build job
        with:
          name: .net-app  # Ensure consistent name

      - name: List contents of downloaded artifact (verification)
        run: dir ./  # Optional verification step
        shell: pwsh  # Optional for PowerShell commands

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'jus365'
          slot-name: 'production'
          package: .
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_5f50f15d78ea413f9dd0fc710fd36446 }}

      - name: Install dotnet-ef tool (optional, if not pre-installed)
        run: dotnet tool install --global dotnet-ef

      - name: Apply Entity Framework Core Migrations
        # Replace "/path/to/deployment" with the actual path on the server (consider full path)
        run: |
          dotnet ef database update --project "/path/to/deployment/Jus 365.csproj" --context ApplicationDbContext
        env:
          ASPNETCORE_ENVIRONMENT: 'Production'
          ConnectionStrings__DefaultConnection: ${{ secrets.DefaultConnection }}
