name: Test Secret

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Test Secret
        run: echo "Test Secret: ${{ secrets.TEST_SECRET }}"
