name: Build and Deploy ASP.NET Core App to Azure Web App - jus365

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  deploy:
    runs-on: windows-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      
      - name: List files in myapp directory
        run: dir ./

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      - name: Apply Entity Framework Core Migrations
        run: |
          dotnet ef database update --project "./myapp/Jus 365.csproj" --context ApplicationDbContext
        env:
          ASPNETCORE_ENVIRONMENT: 'Production'
          ConnectionStrings__DefaultConnection: ${{ secrets.DefaultConnection }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'jus365'
          slot-name: 'production'
          package: ./myapp
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_5f50f15d78ea413f9dd0fc710fd36446 }}
